# Generated by Django 6.0.5 on 2026-05-27 06:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Task title", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Task description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="todo",
                        help_text="Current task status",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        help_text="Task priority",
                        max_length=10,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, help_text="Due date", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_changed",
                    models.CharField(
                        help_text="Name of field that changed", max_length=50
                    ),
                ),
                (
                    "old_value",
                    models.CharField(
                        blank=True, help_text="Previous value", max_length=255
                    ),
                ),
                (
                    "new_value",
                    models.CharField(blank=True, help_text="New value", max_length=255),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
    ]
