# Generated by Django 5.2.5 on 2026-05-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("MEMBER", "Member")],
                default="MEMBER",
                help_text="Global role used for API access control.",
                max_length=10,
            ),
        ),
    ]
